# Form implementation generated from reading ui file 'LecturesWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QLabel


class ClickableLabel(QLabel):
    clicked = pyqtSignal()

    def mousePressEvent(self, event):
        self.clicked.emit()

class Ui_LecturesWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 851, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mainPage = ClickableLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        self.mainPage.setFont(font)
        self.mainPage.setObjectName("mainPage")
        self.horizontalLayout.addWidget(self.mainPage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lab1 = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.lab1.setObjectName("lab1")
        self.horizontalLayout.addWidget(self.lab1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lab2 = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.lab2.setObjectName("lab2")
        self.horizontalLayout.addWidget(self.lab2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lab3 = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.lab3.setObjectName("lab3")
        self.horizontalLayout.addWidget(self.lab3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.lectures = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.lectures.setFont(font)
        self.lectures.setObjectName("lectures")
        self.horizontalLayout.addWidget(self.lectures)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.about = ClickableLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.horizontalLayout.addWidget(self.about)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 831, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 100, 831, 431))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 812, 1128))
        self.scrollAreaWidgetContents.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.line_3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FractalWindow"))
        self.mainPage.setText(_translate("MainWindow", "Main page"))
        self.lab1.setText(_translate("MainWindow", "Lab 1"))
        self.lab2.setText(_translate("MainWindow", "Lab 2"))
        self.lab3.setText(_translate("MainWindow", "Lab 3"))
        self.lectures.setText(_translate("MainWindow", "Lectures"))
        self.about.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "Lectures"))
        self.label_2.setText(_translate("MainWindow", "Fractals"))
        self.label_3.setText(_translate("MainWindow", "Fractals are complex geometric shapes that exhibit self-similarity at different scales. They are generated through iterative mathematical processes, resulting in intricate patterns and structures. The term \"fractal\" was coined by mathematician Benoît B. Mandelbrot in 1975. Fractals can be found in various natural phenomena, such as clouds, mountains, and coastlines, as well as in computer-generated images. Mandelbrot set is one of the most famous fractals, created by iterating a simple mathematical formula. It produces intricate and infinitely detailed patterns, regardless of the level of magnification. Fractals have applications in diverse fields, including mathematics, physics, computer graphics, and art. They are also used to model and understand complex systems in nature, finance, and science. The beauty of fractals lies in their ability to represent complexity through simple rules, making them a fascinating subject of study and a source of inspiration in both scientific and artistic endeavors."))
        self.label_4.setText(_translate("MainWindow", "Color Schemes"))
        self.label_5.setText(_translate("MainWindow", "Color schemes are essential in visual design, providing a systematic way to organize and represent colors. Several color models and schemes are commonly used, each with its unique approach to defining and organizing colors. Here are brief descriptions of some prominent color schemes:\n"
"\n"
"RGB (Red, Green, Blue): In the RGB color model, colors are created by combining different intensities of red, green, and blue light. It is widely used in electronic displays, such as monitors and screens.\n"
"\n"
"CMYK (Cyan, Magenta, Yellow, Black): CMYK is a subtractive color model used in color printing. It represents colors by subtracting varying percentages of cyan, magenta, yellow, and black ink. This model is essential in the printing industry.\n"
"\n"
"HSL (Hue, Saturation, Lightness): HSL represents colors in terms of their hue (the type of color), saturation (intensity or vividness), and lightness (brightness or darkness). It is often used in graphic design and web development.\n"
"\n"
"HSV (Hue, Saturation, Value): Similar to HSL, the HSV model represents colors using hue, saturation, and value. The key difference is that HSV uses value instead of lightness, and it is often preferred in computer graphics and image editing.\n"
"\n"
"Hexadecimal Color Code: Commonly used in web design, the hexadecimal color code represents RGB values using a base-16 system. It is expressed as a six-digit code preceded by a hash symbol (#), where each pair of digits represents the intensity of red, green, and blue, respectively.\n"
"\n"
"These color schemes provide a standardized way to communicate and work with colors across various platforms and industries, ensuring consistency and accuracy in visual representations. Designers and developers often choose color schemes based on the specific requirements of a project and the intended emotional or visual impact."))
        self.label_6.setText(_translate("MainWindow", "Moving images"))
        self.label_7.setText(_translate("MainWindow", "Affine transformations are mathematical techniques used to manipulate and transform images, including moving and distorting them. These transformations preserve parallel lines, ratios of distances, and the overall shape of objects. In the context of moving images, affine transformations can be applied to achieve various visual effects. Here are some key aspects:\n"
"\n"
"Translation: Affine transformations can be used to shift an image horizontally or vertically, effectively moving it across the screen. This is achieved by modifying the coordinates of each pixel in the image.\n"
"\n"
"Rotation: Affine transformations enable the rotation of images around a specified point. This can be used to create dynamic effects, such as spinning or rotating objects within a scene.\n"
"\n"
"Scaling: Images can be resized using affine transformations, either by enlarging or reducing them. Scaling is particularly useful for creating zoom-in or zoom-out effects in moving images.\n"
"\n"
"Shearing: Affine transformations can introduce shearing, a distortion that tilts the image along one axis while keeping the other axis unchanged. This can be applied to create interesting visual effects or simulate perspective changes.\n"
"\n"
"Combining Transformations: Multiple affine transformations can be combined to create more complex movements and distortions. For example, a translation followed by a rotation can simulate an object moving along a curved path.\n"
"\n"
"Affine transformations play a crucial role in computer graphics, animation, and video processing. They provide a versatile set of tools for manipulating visual elements, allowing designers and animators to create dynamic and engaging moving images. These transformations are commonly used in software applications and programming environments that deal with graphics and multimedia."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LecturesWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
