# Form implementation generated from reading ui file 'AboutWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QLabel


class ClickableLabel(QLabel):
    clicked = pyqtSignal()

    def mousePressEvent(self, event):
        self.clicked.emit()

class Ui_AboutWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 851, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mainPage = ClickableLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        self.mainPage.setFont(font)
        self.mainPage.setObjectName("mainPage")
        self.horizontalLayout.addWidget(self.mainPage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lab1 = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.lab1.setObjectName("lab1")
        self.horizontalLayout.addWidget(self.lab1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lab2 = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.lab2.setObjectName("lab2")
        self.horizontalLayout.addWidget(self.lab2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lab3 = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.lab3.setObjectName("lab3")
        self.horizontalLayout.addWidget(self.lab3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.lectures = ClickableLabel(parent=self.horizontalLayoutWidget)
        self.lectures.setObjectName("lectures")
        self.horizontalLayout.addWidget(self.lectures)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.about = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.horizontalLayout.addWidget(self.about)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 831, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.image = QtWidgets.QLabel(parent=self.centralwidget)
        self.image.setGeometry(QtCore.QRect(558, 115, 271, 301))
        self.image.setText("")
        self.image.setObjectName("image")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 531, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 340, 381, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.image.setPixmap(QPixmap())
        self.image.setPixmap(QPixmap("aboutPage/logo.png").scaled(self.image.size(),
                                                                  aspectRatioMode=QtCore.Qt.AspectRatioMode.KeepAspectRatio))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FractalWindow"))
        self.mainPage.setText(_translate("MainWindow", "Main page"))
        self.lab1.setText(_translate("MainWindow", "Lab 1"))
        self.lab2.setText(_translate("MainWindow", "Lab 2"))
        self.lab3.setText(_translate("MainWindow", "Lab 3"))
        self.lectures.setText(_translate("MainWindow", "Lectures"))
        self.about.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "About "))
        self.label_2.setText(_translate("MainWindow", "Who we are?"))
        self.label_3.setText(_translate("MainWindow", "Explore the mesmerizing world of fractals with our cutting-edge program! \n"
"Create stunning, intricate fractal designs, and immerse yourself in a \n"
"dynamic experience that includes customizable color schemes and mesmerizing moving \n"
"images. Unleash your creativity and watch as these mathematical wonders come to life, \n"
"all on our website. "))
        self.label_4.setText(_translate("MainWindow", "F.A.Q"))
        self.label_5.setText(_translate("MainWindow", "What is the homework page? \n"
"    -Homework page is place where you can practice\n"
"What is “Lectures”?\n"
"    -Before exploring the world of mathematics you may read some         information to prepare yourself for homework\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AboutWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
